In [1]:
import numpy as np 


In [12]:
data=[1,2,3,4,5.2]
arr1=np.array(data)
arr1.dtype


dtype('float64')

In [31]:
int_array=np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
In [42]: int_array.astype(calibers.dtype)

In [45]:
arr=np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]])


arr+arr




array([[ 2,  4,  6],
       [ 4,  6,  8],
       [ 6,  8, 10]])

In [46]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [50]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:

arr[5:9]=10        # 5 to 9 on position will be change
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10,  9])

In [56]:
arr2=np.array([
     [1,2,3],
    [2,3,4],
    [3,4,5]
])
arr2[2]
#array([7,8,9])
#arr2[0][2]


array([3, 4, 5])

In [58]:
arr2[0][2]

3

In [62]:
names = np.array(['bob','shi','pink','like','tik'])
data = np.random(7,4)
names

TypeError: 'module' object is not callable